# a build stage to get pulumi
FROM python:3.11-slim as getpulumi

RUN apt-get update && apt-get install -y curl && \
    curl -fsSL https://get.pulumi.com | sh

# a build stage to get pypi dependencies
FROM python:3.11-slim as pypi

ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY pulumi_requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r pulumi_requirements.txt

# the final build stage which copies pulumi and pypi dependencies into the final container
FROM python:3.11-slim

RUN mkdir -p /root/.pulumi/bin

COPY --from=getpulumi /root/.pulumi/bin/* /root/.pulumi/bin/.

ENV PATH="$PATH:/root/.pulumi/bin"
ENV VIRTUAL_ENV=/opt/venv

COPY --from=pypi /opt/venv /opt/venv

ENV PATH="$VIRTUAL_ENV/bin:$PATH"
