FROM python:3.11-slim
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y curl python3-venv git && \
    curl -fsSL https://get.pulumi.com | sh

ENV PATH="$PATH:/root/.pulumi/bin"

WORKDIR /usr/src/app

COPY pulumi_requirements.txt .

RUN python -m venv venv
RUN source venv/bin/activate && pip install --upgrade pip && \
    pip install -r pulumi_requirements.txt
